### PR TITLE
Update null to undefined in ts-generator.ts

### LINKED ISSUE #50: Nullable field causing type assignment error
Hey @divyenduz @timsuchanek 
Steps to reproduce

Use below schema.graphql and yield fresh interfaces and scaffold.
```
type Query {
  me: User
}

type Mutation {
  signup(name: String!, email: String!, password: String!): AuthPayload!
  login(email: String!, password: String!): AuthPayload!
}

type AuthPayload {
  token: String!
  user: User!
}

# The `User` type is a reduced version ("mask") of the `User` type from the data model (and database schema).
# It does not expose the `createdAt`, `updatedAt` and `password` fields.
type User {
  id: ID!
  email: String!
  name: String
}

```

Following type error is produced 
screenshot 9

```
{
	"resource": "/c:/Users/jas/play/prt2/src/resolvers/User.ts",
	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "Type '(parent: UserParent) => string | undefined' is not assignable to type '(parent: UserParent, args: {}, ctx: Context, info: GraphQLResolveInfo) => string | Promise<string | null> | null'.\n  Type 'string | undefined' is not assignable to type 'string | Promise<string | null> | null'.\n    Type 'undefined' is not assignable to type 'string | Promise<string | null> | null'.",
	"source": "ts",
	"startLineNumber": 13,
	"startColumn": 3,
	"endLineNumber": 13,
	"endColumn": 7,
	"relatedInformation": [
		{
			"startLineNumber": 138,
			"startColumn": 5,
			"endLineNumber": 138,
			"endColumn": 9,
			"message": "The expected type comes from property 'name' which is declared here on type 'Type<TypeMap>'",
			"resource": "/c:/Users/jas/play/prt2/src/generated/resolvers.ts"
		}
	]
}
```

### PR DESCRIPTION
**Pull request by jas99**
Fixes #50

### CODE REVIEW

**Comment by divyenduz** [comment]
@jas99 : Can you also bump the snapshot tests please 🙏

**Comment by jas99** [comment]
Yup will do that; but I also have to update scaffold.

@divyenduz I was just wondering if you want to use undefined exclusively? Or thr is some reason you are using null?

**Comment by jas99** [comment]
@divyenduz #50 also have other interface issue, at this point I am more inclined to scrap this PR, I think it will require some more work on your part anyways.

Thx

**Comment by jas99** [comment]
PR move to #52

**Pull request closed without merging**
